### ISSUE TITLE
Travis Rake failed

### ISSUE THREAD

**Issue by diridari** [ob-fun-ws17/studienarbeit-sorted-binary-tree#1]
Guten Tag Herr Braun,
ich habe ein Problem mit Travis. 
Rake bricht den Build immer ab.
vielen Dank

**Comment by obcode** [comment]
Sie müssen auch mit stack und nicht mit Rake bauen.

Schauen Sie mal unter https://docs.haskellstack.org/en/stable/travis_ci/

Beispiel das funktioniert: https://github.com/obcode/plexams/blob/master/.travis.yml

HTH

**Comment by obcode** [comment]
Bitte keine E-Mails vom Travis an **mich**!
